name: unison-parser-typechecker
github: unisonweb/unison
copyright: Copyright (C) 2013-2021 Unison Computing, PBC and contributors

ghc-options: -Wall -O0 -fno-warn-name-shadowing -fno-warn-missing-pattern-synonym-signatures

flags:
  optimized:
    manual: true
    default: true
  arraychecks:
    manual: true
    default: false

when:
  - condition: flag(optimized)
    ghc-options: -funbox-strict-fields -O2
  - condition: flag(arraychecks)
    cpp-options: -DARRAY_CHECK

dependencies:
  - ListLike
  - aeson
  - ansi-terminal
  - asn1-encoding
  - asn1-types
  - async
  - atomic-primops
  - base
  - base16 >= 0.2.1.0
  - base64-bytestring
  - basement
  - binary
  - bytes
  - bytestring
  - bytestring-to-vector
  - cereal
  - clock
  - concurrent-output
  - configurator
  - containers >= 0.6.3
  - cryptonite
  - data-default
  - data-memocombinators
  - deepseq
  - directory
  - either
  - errors
  - exceptions
  - extra
  - filelock
  - filepath
  - fingertree
  - fuzzyfind
  - free
  - generic-lens
  - hashable
  - hashtables
  - haskeline
  - http-client
  - http-media
  - http-types
  - IntervalMap
  - iproute
  - lens
  - lucid
  - megaparsec
  - memory
  - mmorph
  - monad-validate
  - mtl
  - mutable-containers
  - murmur-hash
  - mwc-random
  - natural-transformation
  - network
  - network-simple
  - network-udp
  - network-uri
  - nonempty-containers
  - open-browser
  - openapi3
  - optparse-applicative
  - pem
  - pretty-simple
  - primitive
  - process
  - random >= 1.2.0
  - raw-strings-qq
  - recover-rtti
  - regex-base
  - regex-tdfa
  - safe
  - safe-exceptions
  - semialign
  - semigroups
  - servant
  - servant-client
  - servant-docs
  - servant-openapi3
  - servant-server
  - shellmet
  - stm
  - tagged
  - temporary
  - terminal-size >= 0.3.3
  - text
  - text-short
  - these
  - time
  - tls
  - transformers
  - unicode-show
  - unison-codebase
  - unison-codebase-sqlite
  - unison-codebase-sqlite-hashing-v2
  - unison-codebase-sync
  - unison-core
  - unison-core1
  - unison-hash
  - unison-hashing-v2
  - unison-prelude
  - unison-pretty-printer
  - unison-sqlite
  - unison-syntax
  - unison-util-base32hex
  - unison-util-bytes
  - unison-util-cache
  - unison-util-relation
  - unison-util-rope
  - unison-util-serialization
  - unliftio
  - uuid
  - uri-encode
  - utf8-string
  - vector
  - wai
  - warp
  - witch
  - witherable
  - crypton-x509
  - crypton-x509-store
  - crypton-x509-system
  - yaml
  - zlib

library:
  source-dirs: src
  when:
    - condition: false
      other-modules: Paths_unison_parser_typechecker

tests:
  parser-typechecker-tests:
    source-dirs: tests
    main: Suite.hs
    ghc-options: -W -threaded -rtsopts "-with-rtsopts=-N -T" -v0
    dependencies:
      - code-page
      - easytest
      - filemanip
      - split
      - hex-text
      - unison-parser-typechecker
    when:
      - condition: false
        other-modules: Paths_unison_parser_typechecker

default-extensions:
  - ApplicativeDo
  - BangPatterns
  - BlockArguments
  - DeriveAnyClass
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DerivingStrategies
  - DerivingVia
  - DoAndIfThenElse
  - DuplicateRecordFields
  - FlexibleContexts
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - ImportQualifiedPost
  - LambdaCase
  - MultiParamTypeClasses
  - NamedFieldPuns
  - OverloadedLabels
  - OverloadedRecordDot
  - OverloadedStrings
  - PatternSynonyms
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - ViewPatterns
