name: unison-parser-typechecker
github: unisonweb/unison
copyright: Copyright (C) 2013-2021 Unison Computing, PBC and contributors

ghc-options: -Wall -O0 -fno-warn-name-shadowing -fno-warn-missing-pattern-synonym-signatures

flags:
  optimized:
    manual: true
    default: true

when:
  - condition: flag(optimized)
    ghc-options: -funbox-strict-fields -O2

dependencies:
  - aeson
  - ansi-terminal
  - async
  - base
  - base16 >= 0.2.1.0
  - base64-bytestring
  - basement
  - binary
  - bytes
  - bytestring
  - bytestring-to-vector
  - cereal
  - clock
  - configurator
  - containers >= 0.6.3
  - cryptonite
  - data-default
  - data-memocombinators
  - deepseq
  - directory
  - either
  - errors
  - exceptions
  - extra
  - filepath
  - fingertree
  - fsnotify
  - fuzzyfind
  - generic-lens
  - generic-monoid
  - hashable
  - hashtables
  - haskeline
  - here
  - http-client
  - http-media
  - http-types
  - lens
  - ListLike
  - lucid
  - megaparsec >= 5.0.0 && < 7.0.0
  - memory
  - mmorph
  - monad-validate
  - mtl
  - mutable-containers
  - mwc-random
  - NanoID
  - natural-transformation
  - network
  - network-simple
  - nonempty-containers
  - open-browser
  - openapi3
  - optparse-applicative >= 0.16.1.0
  - pem
  - prelude-extras
  - pretty-simple
  - primitive
  - process
  - random >= 1.2.0
  - raw-strings-qq
  - regex-base
  - regex-tdfa
  - safe
  - safe-exceptions
  - semialign
  - servant
  - servant-client
  - servant-docs
  - servant-openapi3
  - servant-server
  - shellmet
  - stm
  - strings
  - tagged
  - temporary
  - terminal-size
  - text
  - text-short
  - these
  - time
  - tls
  - transformers
  - unicode-show
  - unison-codebase
  - unison-codebase-sqlite
  - unison-codebase-sync
  - unison-core
  - unison-core1
  - unison-prelude
  - unison-pretty-printer
  - unison-sqlite
  - unison-util
  - unison-util-base32hex
  - unison-util-relation
  - unison-util-serialization
  - unliftio
  - uri-encode
  - utf8-string
  - vector
  - wai
  - warp
  - x509
  - x509-store
  - x509-system
  - yaml
  - zlib

library:
  source-dirs: src

tests:
  parser-typechecker-tests:
    source-dirs: tests
    main: Suite.hs
    ghc-options: -W -threaded -rtsopts "-with-rtsopts=-N -T" -v0
    dependencies:
      - code-page
      - easytest
      - filemanip
      - split
      - unison-parser-typechecker

default-extensions:
  - ApplicativeDo
  - BangPatterns
  - BlockArguments
  - DeriveAnyClass
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DerivingStrategies
  - DerivingVia
  - DoAndIfThenElse
  - DuplicateRecordFields
  - FlexibleContexts
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - NamedFieldPuns
  - OverloadedStrings
  - PatternSynonyms
  - RankNTypes
  - ScopedTypeVariables
  - TupleSections
  - TypeApplications
  - ViewPatterns
