name: unison-codebase-sqlite
github: unisonweb/unison

library:
  when:
    - condition: false
      other-modules: Paths_unison_codebase_sqlite
  source-dirs: .

extra-source-files:
  - sql/*

dependencies:
  - Only
  - base
  - bytes
  - bytestring
  - containers
  - extra
  - generic-lens
  - here
  - lens
  - monad-validate
  - mtl
  - neat-interpolation
  - network-uri
  - network-uri-orphans-sqlite
  - nonempty-containers
  - safe
  - text
  - transformers
  - unison-codebase
  - unison-codebase-sync
  - unison-core
  - unison-core-orphans-sqlite
  - unison-hash
  - unison-hash-orphans-sqlite
  - unison-prelude
  - unison-sqlite
  - unison-util-base32hex
  - unison-util-cache
  - unison-util-serialization
  - unison-util-term
  - unliftio
  - uuid
  - uuid-orphans-sqlite
  - vector

default-extensions:
  - ApplicativeDo
  - BangPatterns
  - BlockArguments
  - ConstraintKinds
  - DeriveAnyClass
  - DeriveFunctor
  - DeriveFoldable
  - DeriveTraversable
  - DeriveGeneric
  - DerivingStrategies
  - DerivingVia
  - DoAndIfThenElse
  - DuplicateRecordFields
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - LambdaCase
  - MultiParamTypeClasses
  - NamedFieldPuns
  - OverloadedStrings
  - PatternSynonyms
  - QuasiQuotes
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeFamilyDependencies
  - TypeOperators
  - ViewPatterns
