name: unison-cli
github: unisonweb/unison
copyright: Copyright (C) 2013-2018 Unison Computing, PBC and contributors

flags:
  optimized:
    manual: true
    default: false

ghc-options: -Wall

dependencies:
  - IntervalMap
  - ListLike
  - aeson
  - aeson-pretty
  - ansi-terminal
  - async
  - base
  - bytes
  - bytestring
  - concurrent-output
  - configurator
  - containers >= 0.6.3
  - cryptonite
  - directory
  - either
  - errors
  - exceptions
  - extra
  - filepath
  - free
  - fuzzyfind
  - friendly-time
  - generic-lens
  - haskeline
  - here
  - http-client >= 0.7.6
  - http-client-tls
  - http-types
  - jwt
  - ki
  - lens
  - lock-file
  - lsp
  - lsp-types
  - megaparsec
  - memory
  - mtl
  - network-uri
  - network-simple
  - network
  - co-log-core
  - uri-encode
  - nonempty-containers
  - open-browser
  - pretty-simple
  - process
  - random >= 1.2.0
  - recover-rtti
  - regex-tdfa
  - semialign
  - servant
  - servant-client
  - stm
  - text
  - text-rope
  - these
  - time
  - transformers
  - unison-codebase
  - unison-codebase-sqlite
  - unison-codebase-sqlite-hashing-v2
  - unison-core
  - unison-core1
  - unison-hash
  - unison-parser-typechecker
  - unison-prelude
  - unison-pretty-printer
  - unison-share-api
  - unison-sqlite
  - unison-syntax
  - unison-util-base32hex
  - unison-util-relation
  - unliftio
  - unordered-containers
  - vector
  - witherable
  - wai
  - warp
  - witherable

library:
  source-dirs: src
  when:
    - condition: '!os(windows)'
      dependencies: unix
    - condition: false
      other-modules: Paths_unison_cli

tests:
  cli-tests:
    when:
      - condition: false
        other-modules: Paths_unison_cli
    dependencies:
      - code-page
      - easytest
      - here
      - shellmet
      - temporary
      - unison-cli
    main: Main.hs
    source-dirs: tests

executables:
  unison:
    when:
      - condition: false
        other-modules: Paths_unison_cli
    source-dirs: unison
    main: Main.hs
    ghc-options: -threaded -rtsopts "-with-rtsopts=-I0 -N -qn4 -qg1 -T" -optP-Wno-nonportable-include-path
    dependencies:
      - code-page
      - optparse-applicative >= 0.16.1.0
      - shellmet
      - template-haskell
      - temporary
      - unison-cli

  transcripts:
    when:
      - condition: false
        other-modules: Paths_unison_cli
    source-dirs: transcripts
    main: Transcripts.hs
    ghc-options: -threaded -rtsopts "-with-rtsopts=-I0 -N -qn4 -qg1" -v0
    dependencies:
      - code-page
      - easytest
      - process
      - shellmet
      - unison-cli

  cli-integration-tests:
    when:
      - condition: false
        other-modules: Paths_unison_cli
    source-dirs: integration-tests
    main: Suite.hs
    ghc-options: -W -threaded -rtsopts "-with-rtsopts=-N -T" -v0
    dependencies:
      - code-page
      - easytest
      - process
      - shellmet
      - time
    build-tools:
      - unison-cli:unison

when:
  - condition: flag(optimized)
    ghc-options: -O2 -funbox-strict-fields

default-extensions:
  - ApplicativeDo
  - BangPatterns
  - BlockArguments
  - DeriveAnyClass
  - DeriveFunctor
  - DeriveFoldable
  - DeriveTraversable
  - DeriveGeneric
  - DerivingStrategies
  - DerivingVia
  - DoAndIfThenElse
  - DuplicateRecordFields
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - LambdaCase
  - MultiParamTypeClasses
  - NamedFieldPuns
  - NumericUnderscores
  - OverloadedLabels
  - OverloadedStrings
  - PatternSynonyms
  - RankNTypes
  - ScopedTypeVariables
  - TupleSections
  - TypeApplications
  - ViewPatterns
