pull_request_rules:
  - name: automatic merge on CI success and review
    conditions:
      - status-success=ubuntu-20.04
      # - status-success=ubuntu-18.04
      - status-success=macOS-11.0
      - status-success=macOS-10.15
      - status-success=windows-2019
      - label=ready-to-merge
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: merge
      label:
        remove: ["ready-to-merge"]
#   - name: delete head branch after merge
#     conditions: []
#     actions:
#       delete_head_branch: {}
