pull_request_rules:
  - name: automatic merge on CI success and review
    conditions:
      - check-success=check-contributor
      - check-success=build ucm (ubuntu-20.04)
      - check-success=build ucm (macos-13)
      - check-success=build ucm (windows-2019)
      - check-success=run transcripts (ubuntu-20.04)
      - check-success=run transcripts (macos-13)
      - check-success=run transcripts (windows-2019)
      - check-success=run interpreter tests (ubuntu-20.04)
      - check-success=run interpreter tests (macos-13)
      # - check-success=run interpreter tests (windows-2019)
      - check-success=generate jit source
      - check-success=build jit binary / build jit binary (ubuntu-20.04)
      - check-success=build jit binary / build jit binary (macos-13)
      - check-success=build jit binary / build jit binary (windows-2019)
      - check-success=test jit / test jit (ubuntu-20.04)
      - check-success=test jit / test jit (macos-13)
      # - check-success=test jit / test jit (windows-2019)
      - label=ready-to-merge
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: merge
      label:
        remove: ["ready-to-merge"]
#   - name: delete head branch after merge
#     conditions: []
#     actions:
#       delete_head_branch: {}
