# https://docs.haskellstack.org/en/stable/travis_ci/
# run on containerized infrastructure hopefully
dist: trusty
sudo: false
language: generic


# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack
  - $HOME/.ivy2/cache
  - $HOME/.sbt
  - /var/cache/apt/archives/ # deb files

before_cache:
# Cleanup the cached directories to avoid unnecessary cache updates
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
- find $HOME/.sbt        -name "*.lock"               -print -delete

before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
# Configure stack to use the system GHC installation
- stack config set system-ghc --global true
- export PATH=/opt/ghc/8.0.1/bin:$PATH
- stack setup

script:
  - stack --no-terminal build && stack --no-terminal exec tests
  - pushd runtime-jvm
  - sbt main/test:run
  - popd

addons:
  apt:
    sources:
      - hvr-ghc
      - sourceline: 'ppa:hvr/ghc' # PPA of Haskell packages
    packages:
      - ghc-8.4.3
      - libc6
      - libc6-dev
install:
  - travis_wait stack --no-terminal setup
  - travis_wait stack --no-terminal test --only-snapshot
