# https://docs.haskellstack.org/en/stable/travis_ci/
# run on containerized infrastructure hopefully
dist: trusty
sudo: false
language: generic


# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack
  - $HOME/.ivy2/cache
  - $HOME/.sbt

before_cache:
# Cleanup the cached directories to avoid unnecessary cache updates
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
- find $HOME/.sbt        -name "*.lock"               -print -delete

before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
# Configure stack to use the system GHC installation
- stack config set system-ghc --global true
- export PATH=/opt/ghc/8.4.3/bin:$PATH

install:
  # - stack ghc -- --version
  - travis_wait stack --no-terminal --no-install-ghc setup
  - travis_wait stack --no-terminal --no-install-ghc test --only-snapshot
  - travis_wait stack --no-terminal --no-install-ghc build

script:
  - stack --no-terminal exec tests
  - pushd runtime-jvm
  - sbt main/test:run
  - popd


after_script: # diagnostic stuff, temporary
  - find $HOME/.stack
  - find $HOME/.ivy2/cache
  - find $HOME/.sbt
  - ls -ld /opt/ghc/*

addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      - ghc-8.4.3
      - libc6
      - libc6-dev
