flags: {}

allow-newer: true # async package has needlessly strict upper bound

packages:
- yaks/parsec-layout
- yaks/easytest
- parser-typechecker

#compiler-check: match-exact
resolver: lts-11.9
compiler: ghc-8.4.2

extra-deps:
#  - applicative-extras-0.1.8
#  - ctrie-0.1.0.3
- cryptonite-0.17
- GraphSCC-1.0.4
- base58-bytestring-0.1.0

#extra-include-dirs:
#- /usr/local/include
#extra-lib-dirs:
#- /usr/local/lib
