flags: {}

# allow-newer: true # async package has needlessly strict upper bound

allow-different-user: true

packages:
- yaks/easytest
- parser-typechecker
- unison-core

#compiler-check: match-exact
resolver: snapshot.yaml

ghc-options:
 # All packages
 "$locals": -Werror -Wno-type-defaults #-freverse-errors
