name: unison-syntax
github: unisonweb/unison
copyright: Copyright (C) 2013-2022 Unison Computing, PBC and contributors

ghc-options: -Wall

library:
  source-dirs: src
  when:
    - condition: false
      other-modules: Paths_unison_syntax

  dependencies:
    - base
    - bytes
    - containers
    - cryptonite
    - deriving-compat
    - extra
    - free
    - lens
    - megaparsec
    - mtl
    - parser-combinators
    - text
    - unison-core
    - unison-core1
    - unison-hash
    - unison-prelude
    - unison-util-base32hex
    - unison-util-bytes

tests:
  syntax-tests:
    when:
      - condition: false
        other-modules: Paths_unison_syntax
    dependencies:
      - base
      - code-page
      - easytest
      - megaparsec
      - unison-core1
      - unison-prelude
      - unison-syntax
      - unison-util-recursion
      - text
    main: Main.hs
    source-dirs: test

default-extensions:
  - ApplicativeDo
  - BangPatterns
  - BlockArguments
  - DeriveAnyClass
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DerivingStrategies
  - DerivingVia
  - DoAndIfThenElse
  - DuplicateRecordFields
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GeneralizedNewtypeDeriving
  - ImportQualifiedPost
  - LambdaCase
  - MultiParamTypeClasses
  - NamedFieldPuns
  - OverloadedStrings
  - PatternSynonyms
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - ViewPatterns
