name: unison-syntax
github: unisonweb/unison
copyright: Copyright (C) 2013-2022 Unison Computing, PBC and contributors

ghc-options: -Wall

dependencies:
  - base
  - bytes
  - containers
  - cryptonite
  - lens
  - megaparsec
  - mtl
  - text
  - unison-core
  - unison-core1
  - unison-hash
  - unison-prelude
  - unison-util-base32hex
  - unison-util-bytes

library:
  source-dirs: src
  when:
    - condition: false
      other-modules: Paths_unison_syntax

tests:
  syntax-tests:
    when:
      - condition: false
        other-modules: Paths_unison_syntax
    dependencies:
      - code-page
      - easytest
      - unison-syntax
    main: Main.hs
    source-dirs: test

default-extensions:
  - ApplicativeDo
  - BangPatterns
  - BlockArguments
  - DeriveAnyClass
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DerivingStrategies
  - DerivingVia
  - DoAndIfThenElse
  - DuplicateRecordFields
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GeneralizedNewtypeDeriving
  - ImportQualifiedPost
  - LambdaCase
  - MultiParamTypeClasses
  - NamedFieldPuns
  - OverloadedStrings
  - PatternSynonyms
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - ViewPatterns
