name: unison-merge
github: unisonweb/unison
copyright: Copyright (C) 2013-2018 Unison Computing, PBC and contributors

ghc-options: -Wall

dependencies:
  - base
  - containers
  - lens
  - mtl
  - nonempty-containers
  - semialign
  - semigroups
  - text
  - these
  - transformers
  - unison-core
  - unison-core1
  - unison-hash
  - unison-parser-typechecker
  - unison-prelude
  - unison-pretty-printer
  - unison-syntax
  - unison-util-relation
  - witch
  - witherable

library:
  # exposed-modules:
  #   # TODO probably whittle this down to one
  #   - Unison.Merge
  #   - Unison.Merge2
  source-dirs: src
  when:
    - condition: false
      other-modules: Paths_unison_merge

default-extensions:
  - ApplicativeDo
  - BangPatterns
  - BlockArguments
  - DeriveAnyClass
  - DeriveFunctor
  - DeriveFoldable
  - DeriveTraversable
  - DeriveGeneric
  - DerivingStrategies
  - DerivingVia
  - DoAndIfThenElse
  - DuplicateRecordFields
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - ImportQualifiedPost
  - InstanceSigs
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NumericUnderscores
  - OverloadedLabels
  - OverloadedRecordDot
  - OverloadedStrings
  - PatternSynonyms
  - QuantifiedConstraints
  - RankNTypes
  - ScopedTypeVariables
  - TupleSections
  - TypeApplications
  - ViewPatterns
