name: unison-core
github: unisonweb/unison

library:
  source-dirs: .
  when:
    - condition: false
      other-modules: Paths_unison_core

dependencies:
  - base
  - containers
  - rfc5051
  - text
  - vector
  - unison-hash
  - unison-prelude
  - unison-util-base32hex

default-extensions:
  - ApplicativeDo
  - BangPatterns
  - BlockArguments
  - DeriveAnyClass
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DerivingStrategies
  - DerivingVia
  - DoAndIfThenElse
  - FlexibleContexts
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - NamedFieldPuns
  - OverloadedStrings
  - QuantifiedConstraints
  - PatternSynonyms
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - ViewPatterns
