name: unison-runtime
github: unisonweb/unison
copyright: Copyright (C) 2013-2024 Unison Computing, PBC and contributors

ghc-options: -fmax-worker-args=100 -Wall -funbox-strict-fields -O2

flags:
  arraychecks:
    manual: true
    default: false
  stackchecks:
    manual: true
    default: false

  # Run optimization assertion tests, make sure this runs with O2
  optchecks:
    manual: true
    default: false

  # Dumps core for debugging to unison-runtime/.stack-work/dist/<arch>/ghc-x.y.z/build/
  dumpcore:
    manual: true
    default: false

when:
  - condition: flag(arraychecks)
    cpp-options: -DARRAY_CHECK
  - condition: flag(stackchecks)
    cpp-options: -DSTACK_CHECK
  - condition: flag(optchecks)
    ghc-options: -O2
    cpp-options: -DOPT_CHECK
    dependencies:
      - inspection-testing
  - condition: flag(dumpcore)
    ghc-options: -ddump-simpl -ddump-stg-final -ddump-to-file -dsuppress-coercions -dsuppress-idinfo -dsuppress-module-prefixes -ddump-str-signatures -ddump-simpl-stats # -dsuppress-type-applications -dsuppress-type-signatures

library:
  source-dirs: src
  when:
    - condition: false
      other-modules: Paths_unison_runtime

  dependencies:
    - asn1-encoding
    - asn1-types
    - atomic-primops
    - base
    - binary
    - bytes
    - bytestring
    - cereal
    - clock
    - containers >= 0.6.3
    - cryptonite
    - data-default
    - data-memocombinators
    - deepseq
    - directory
    - exceptions
    - filepath
    - iproute
    - lens
    - memory
    - mmorph
    - mtl
    - murmur-hash
    - network
    - network-simple
    - network-udp
    - pem
    - primitive
    - process
    - raw-strings-qq
    - safe-exceptions
    - stm
    - tagged
    - temporary
    - text
    - template-haskell
    - inspection-testing
    - time
    - tls
    - unison-codebase-sqlite
    - unison-core
    - unison-core1
    - unison-hash
    - unison-parser-typechecker
    - unison-prelude
    - unison-pretty-printer
    - unison-syntax
    - unison-util-bytes
    - unison-util-recursion
    - unliftio
    - vector
    - crypton-x509
    - crypton-x509-store
    - crypton-x509-system

tests:
  runtime-tests:
    source-dirs: tests
    main: Suite.hs
    ghc-options: -W -threaded -rtsopts "-with-rtsopts=-N -T" -v0
    when:
      - condition: false
        other-modules: Paths_unison_parser_typechecker
    dependencies:
      - base
      - bytes
      - cereal
      - code-page
      - containers
      - cryptonite
      - directory
      - easytest
      - hedgehog
      - filemanip
      - filepath
      - hex-text
      - lens
      - megaparsec
      - mtl
      - primitive
      - stm
      - text
      - unison-core1
      - unison-hash
      - unison-util-bytes
      - unison-parser-typechecker
      - unison-prelude
      - unison-pretty-printer
      - unison-runtime
      - unison-syntax

default-extensions:
  - ApplicativeDo
  - BangPatterns
  - BlockArguments
  - DeriveAnyClass
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DerivingStrategies
  - DerivingVia
  - DoAndIfThenElse
  - DuplicateRecordFields
  - FlexibleContexts
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - ImportQualifiedPost
  - LambdaCase
  - MultiParamTypeClasses
  - NamedFieldPuns
  - OverloadedLabels
  - OverloadedRecordDot
  - OverloadedStrings
  - PatternSynonyms
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - ViewPatterns
