name: unison-core1
github: unisonweb/unison
copyright: Copyright (C) 2013-2018 Unison Computing, PBC and contributors

library:
  when:
    - condition: false
      other-modules: Paths_unison_core1
  source-dirs: src
  ghc-options: -Wall -fno-warn-name-shadowing -fno-warn-missing-pattern-synonym-signatures -funbox-strict-fields
  dependencies:
    - base
    - bytestring
    - containers >= 0.6.3
    - nonempty-containers
    - cryptonite
    - either
    - extra
    - fuzzyfind
    - generic-lens
    - lens
    - megaparsec
    - memory
    - mtl
    - rfc5051
    - safe
    - text
    - text-builder
    - these
    - transformers
    - unison-core
    - unison-hash
    - unison-prelude
    - unison-util-base32hex
    - unison-util-relation
    - vector
    - witch

tests:
  tests:
    when:
      - condition: false
        other-modules: Paths_unison_core1
    dependencies:
      - base
      - code-page
      - easytest
      - text
      - these
      - unison-core
      - unison-core1
      - unison-prelude
    main: Main.hs
    source-dirs: test

default-extensions:
  - ApplicativeDo
  - BlockArguments
  - DeriveAnyClass
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DerivingStrategies
  - DoAndIfThenElse
  - FlexibleContexts
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - ImportQualifiedPost
  - LambdaCase
  - MultiParamTypeClasses
  - NamedFieldPuns
  - OverloadedStrings
  - PatternSynonyms
  - RankNTypes
  - ScopedTypeVariables
  - TupleSections
  - TypeApplications
  - ViewPatterns

flags:
  optimized:
    manual: true
    default: false

when:
  - condition: flag(optimized)
    ghc-options: -O2 -funbox-strict-fields
