name: unison-core1
github: unisonweb/unison
copyright: Copyright (C) 2013-2018 Unison Computing, PBC and contributors

library:
  when:
    - condition: false
      other-modules: Paths_unison_core1
  source-dirs: src
  ghc-options: -Wall -fno-warn-name-shadowing -fno-warn-missing-pattern-synonym-signatures -funbox-strict-fields
  dependencies:
    - base
    - bytestring
    - containers >= 0.6.3
    - nonempty-containers
    - cryptonite
    - either
    - extra
    - fuzzyfind
    - generic-lens
    - lens
    - prelude-extras
    - memory
    - mtl
    - rfc5051
    - safe
    - text
    - transformers
    - unison-prelude
    - unison-util
    - unison-util-base32hex
    - unison-util-relation
    - vector

default-extensions:
  - ApplicativeDo
  - BlockArguments
  - DeriveFunctor
  - DeriveGeneric
  - DerivingStrategies
  - DoAndIfThenElse
  - FlexibleContexts
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - NamedFieldPuns
  - OverloadedStrings
  - PatternSynonyms
  - ScopedTypeVariables
  - TupleSections
  - TypeApplications
  - ViewPatterns

flags:
  optimized:
    manual: true
    default: false

when:
  - condition: flag(optimized)
    ghc-options: -O2 -funbox-strict-fields
