name: update-transcripts

on:
  workflow_dispatch:

jobs:
  update_transcripts:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        os:
          - macOS-12
    steps:
      - uses: actions/checkout@v4
      - uses: unisonweb/actions/stack/cache/restore@main
        with:
          # take cache from the ci job, read-only
          cache-prefix: ci

      - name: install stack
        uses: unisonweb/actions/stack/install@main
        with:
          stack-version: 2.15.5

      # One of the transcripts fails if the user's git name hasn't been set.
      - name: set git user info
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      - name: build
        run: stack build --fast --no-run-tests --test
      - name: round-trip-tests
        run: |
          stack exec unison transcript unison-src/transcripts-round-trip/main.md
          stack exec unison transcript unison-src/transcripts-manual/rewrites.md
      - name: transcripts
        run: stack exec transcripts
      - name: docs.to-html
        run: |
          stack exec unison transcript unison-src/transcripts-manual/docs.to-html.md
      - name: save transcript changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: rerun transcripts (reminder to rerun CI!)
